from datetime import datetime
from reportlab.platypus import Paragraph
from reportlab.lib.styles import getSampleStyleSheet


styles = getSampleStyleSheet()


def add_footer(story):

    story.append(Paragraph("<br/><br/>", styles["BodyText"]))

    story.append(
        Paragraph(
            "<b>Reviewed By</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            "Dr. Hassan Raza",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            "Consultant Pathologist",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            "<br/>__________________________",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            "Doctor Signature",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            "<br/><br/>",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Generated On : {datetime.now().strftime('%d-%b-%Y %I:%M %p')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            "Generated by AI Diagnostics Lab",
            styles["BodyText"]
        )
    )