import os
from security.digital_signature import generate_signature

def generate_verification_page(report):

    signature = generate_signature(report)

    os.makedirs(
        "output/verification",
        exist_ok=True
    )

    filename = (
        f"output/verification/{report.patient['report_id']}.html"
    )

    html = f"""
<!DOCTYPE html>

<html>

<head>

<title>Report Verification</title>

<style>

body {{
    font-family: Arial, sans-serif;
    background: #f5f5f5;
    padding: 40px;
}}

.container {{
    background: white;
    max-width: 700px;
    margin: auto;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0,0,0,.15);
}}

h1 {{
    color: green;
}}

table {{
    width:100%;
    border-collapse:collapse;
    margin-top:20px;
}}

td {{
    border:1px solid #ccc;
    padding:10px;
}}

.status {{
    margin-top:25px;
    padding:15px;
    background:#e8f5e9;
    border-left:5px solid green;
    font-size:18px;
}}

</style>

</head>

<body>

<div class="container">

<h1>✔ VERIFIED REPORT</h1>

<h2>AI Diagnostics Lab</h2>

<table>

<tr>
<td><b>Report ID</b></td>
<td>{report.patient["report_id"]}</td>
</tr>

<tr>
<td><b>Patient</b></td>
<td>{report.patient["name"]}</td>
</tr>

<tr>
<td><b>Age</b></td>
<td>{report.patient["age"]}</td>
</tr>

<tr>
<td><b>Gender</b></td>
<td>{report.patient["gender"]}</td>
</tr>

<tr>
<td><b>Doctor</b></td>
<td>{report.patient["doctor"]}</td>
</tr>

<tr>
<td><b>Condition</b></td>
<td>{report.condition}</td>
</tr>

<tr>
<td><b>Severity</b></td>
<td>{report.severity}</td>
</tr>

<tr>
<td><b>Digital Signature</b></td>
<td>{signature}</td>
</tr>

</table>

<div class="status">

✔ This report is authentic and was generated by
AI Diagnostics Lab.

</div>

</div>

</body>

</html>
"""

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(html)